/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
// @ts-ignore
import type * as interface from "./interface";
export type { interface };
export type { Rental } from "./Rental";
