/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
export * as interface from "./interface";
export { Rental__factory } from "./Rental__factory";
