name: CDK Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  aws_cdk_main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: npm
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-region: "us-east-1"
          role-to-assume: ${{ secrets.AWS_GITHUB_ACTION_IAM_ROLE }}
          role-session-name: GitHubActions
      - name: Install
        run: npm ci
      - name: Synth
        run: npx cdk synth
      - name: Deploy
        run: npx cdk deploy ResolverGdnStack --require-approval never --exclusively
  aws_cdk_regional_us:
    needs: aws_cdk_main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: npm
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-region: "us-east-1"
          role-to-assume: ${{ secrets.AWS_GITHUB_ACTION_IAM_ROLE }}
          role-session-name: GitHubActions
      - name: Install
        run: npm ci
      - name: Synth
        run: npx cdk synth
      - name: Deploy
        run: npx cdk deploy UnitedStates-RegionalStack --require-approval never --exclusively
  aws_cdk_regional_sg:
    needs: aws_cdk_main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: npm
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-region: "us-east-1"
          role-to-assume: ${{ secrets.AWS_GITHUB_ACTION_IAM_ROLE }}
          role-session-name: GitHubActions
      - name: Install
        run: npm ci
      - name: Synth
        run: npx cdk synth
      - name: Deploy
        run: npx cdk deploy Singapore-RegionalStack --require-approval never --exclusively
  aws_cdk_regional_jp:
    needs: aws_cdk_main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: npm
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-region: "us-east-1"
          role-to-assume: ${{ secrets.AWS_GITHUB_ACTION_IAM_ROLE }}
          role-session-name: GitHubActions
      - name: Install
        run: npm ci
      - name: Synth
        run: npx cdk synth
      - name: Deploy
        run: npx cdk deploy Japan-RegionalStack --require-approval never --exclusively
  aws_cdk_regional_de:
    needs: aws_cdk_main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: npm
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-region: "us-east-1"
          role-to-assume: ${{ secrets.AWS_GITHUB_ACTION_IAM_ROLE }}
          role-session-name: GitHubActions
      - name: Install
        run: npm ci
      - name: Synth
        run: npx cdk synth
      - name: Deploy
        run: npx cdk deploy Germany-RegionalStack --require-approval never --exclusively
